name: Build
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build Win32
        # /p:CharacterSet=Unicode を追加します
        run: msbuild BonDriver_PTx.sln /p:Configuration=Release /p:Platform=Win32 /p:PlatformToolset=v143 /p:WindowsTargetPlatformVersion=10.0 /p:CharacterSet=Unicode
      
      - name: Build x64
        run: msbuild BonDriver_PTx.sln /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=v143 /p:WindowsTargetPlatformVersion=10.0 /p:CharacterSet=Unicode

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: BonDriver_PTx-ST_mod_Unicode_Build
          path: |
            **/*.dll
            **/*.exe
            
